name: DockerHub Publish

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      base_image_tag:
        default: 'bullseye-slim'
        description: 'Base debian image tag to build'
        required: true
        type: string
      nsis_ver:
        default: '3.10'
        description: 'NSIS version to compile'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            # set latest tag for master branch
            type=raw,value=latest

      - name: Push NSIS
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE_TAG=${{ inputs.base_image_tag }}
            NSIS_VER=${{ inputs.nsis_ver }}
          context: .
          push: true
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ github.repository }}:${{ inputs.base_image_tag }}-${{ inputs.nsis_ver }}
            ${{ github.repository }}:latest

      - name: Push NSIS-Log
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE_TAG=${{ inputs.base_image_tag }}-${{ inputs.nsis_ver }}
          context: .
          push: true
          file: Dockerfile.log
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ github.repository }}:${{ inputs.base_image_tag }}-${{ inputs.nsis_ver }}-log
            ${{ github.repository }}:log
            ${{ github.repository }}:log-latest

      - name: Push NSIS-StrLen
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE_TAG=${{ inputs.base_image_tag }}-${{ inputs.nsis_ver }}
          context: .
          push: true
          file: Dockerfile.strlen
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ github.repository }}:${{ inputs.base_image_tag }}-${{ inputs.nsis_ver }}-strlen
            ${{ github.repository }}:strlen
            ${{ github.repository }}:strlen-latest
