name: DockerHub Publish

on:
  push:
    branches:
      - main
    tags:
      - *
  workflow_call:
    inputs:
      base_image_tag:
        default: 'bullseye-slim'
        description: 'Base debian image tag to build'
        required: true
        type: string
      nsis_ver:
        default: '3.08'
        description: 'NSIS version to compile'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Docker Hub Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: albertowd/nsis
      - name: Push NSIS
        uses: docker/build-push-action@v3.1.0
        with:
          build_args: BASE_IMAGE_TAG=${{ inputs.base_image_tag }},NSIS_VER=${{ inputs.nsis_ver }}
          context: .
          push: true
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          tags: albertowd/nsis:${{ base_image_tag }}-${{ nsis_ver }},albertowd/nsis:latest
      - name: Push NSIS-Log
        uses: docker/build-push-action@v3.1.0
        with:
          build_args: BASE_IMAGE_TAG=${{ inputs.base_image_tag }}
          context: .
          push: true
          file: Dockerfile.log
          labels: ${{ steps.meta.outputs.labels }}
          tags: albertowd/nsis:${{ base_image_tag }}-${{ nsis_ver }}-log,albertowd/nsis:log,albertowd/nsis:log-latest
      - name: Push NSIS-StrLen
        uses: docker/build-push-action@v3.1.0
        with:
          build_args: BASE_IMAGE_TAG=${{ inputs.base_image_tag }}
          context: .
          push: true
          file: Dockerfile.strlen
          labels: ${{ steps.meta.outputs.labels }}
          tags: albertowd/nsis:${{ base_image_tag }}-${{ nsis_ver }}-strlen,albertowd/nsis:strlen,albertowd/nsis:strlen-latest
